import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../models/habit.dart';
import '../models/task.dart';
import '../services/storage_service.dart';

class ProgressScreen extends StatefulWidget { const ProgressScreen({super.key}); @override State<ProgressScreen> createState()=>_ProgressScreenState(); }
class _ProgressScreenState extends State<ProgressScreen>{
  List<HabitItem> habits=[];List<TaskItem> tasks=[];bool loading=true;
  @override void initState(){super.initState();StorageService.changes.addListener(_refreshFromStorage);load();}
  void _refreshFromStorage(){if(mounted)load();}
  @override void dispose(){StorageService.changes.removeListener(_refreshFromStorage);super.dispose();}
  Future<void> load()async{final r=await Future.wait([StorageService.loadHabits(),StorageService.loadTasks()]);if(mounted)setState((){habits=r[0] as List<HabitItem>;tasks=r[1] as List<TaskItem>;loading=false;});}
  String key(DateTime d)=>DateFormat('yyyy-MM-dd').format(d); int get master=>habits.isEmpty?0:habits.map((h)=>h.streakCount).reduce((a,b)=>a<b?a:b);
  @override Widget build(BuildContext context){final complete=tasks.where((t)=>t.isCompleted).length;return Scaffold(backgroundColor:const Color(0xFFF7F8FC),appBar:AppBar(title:const Text('Progress',style:TextStyle(fontWeight:FontWeight.w800))),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.fromLTRB(20,10,20,96),children:[Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF172554),Color(0xFF4F46E5)]),borderRadius:BorderRadius.circular(24)),child:Row(children:[Container(width:58,height:58,alignment:Alignment.center,decoration:const BoxDecoration(color:Color(0x33FFFFFF),shape:BoxShape.circle),child:const Text('🔥',style:TextStyle(fontSize:29))),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('$master day master streak',style:const TextStyle(color:Colors.white,fontSize:21,fontWeight:FontWeight.w800)),const SizedBox(height:4),const Text('Consistency compounds. Keep the chain alive.',style:TextStyle(color:Color(0xFFC7D2FE),fontSize:12))]))])),const SizedBox(height:24),header('Your consistency','Last 14 weeks'),const SizedBox(height:12),heatmap(),const SizedBox(height:24),header('Track streaks','Tap a habit to check in'),const SizedBox(height:10),...habits.map(habit),const SizedBox(height:22),header('Milestones','Unlocked as you show up'),const SizedBox(height:10),Wrap(spacing:10,runSpacing:10,children:[badge('3-Day Spark',3,'✨'),badge('7-Day Habit',7,'⚡'),badge('14-Day Iron Will',14,'🛡️'),badge('30-Day Beast',30,'🐺'),badge('60-Day Engineer',60,'🧠'),badge('100-Day Legend',100,'🏆')]),const SizedBox(height:24),Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18)),child:Row(children:[const Icon(Icons.task_alt,color:Color(0xFF10B981)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Tasks completed',style:TextStyle(fontWeight:FontWeight.w700,color:Color(0xFF172033))),Text('$complete tasks marked complete',style:const TextStyle(fontSize:12,color:Color(0xFF64748B)))])),Text('$complete',style:const TextStyle(fontSize:24,fontWeight:FontWeight.w800,color:Color(0xFF172033)))]))])));}
  Widget header(String a,String b)=>Row(children:[Text(a,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w800,color:Color(0xFF172033))),const Spacer(),Text(b,style:const TextStyle(fontSize:12,color:Color(0xFF64748B)))]);
  Widget heatmap(){final dates=List.generate(98,(i)=>DateTime.now().subtract(Duration(days:97-i)));final marked=habits.expand((h)=>h.completedDates).toSet();return Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Wrap(spacing:4,runSpacing:4,children:dates.map((d){final hit=marked.contains(key(d));final recent=d.isAfter(DateTime.now().subtract(const Duration(days:7)));return Tooltip(message:DateFormat('d MMM').format(d),child:Container(width:17,height:17,decoration:BoxDecoration(color:hit?const Color(0xFF4F46E5):recent?const Color(0xFFE0E7FF):const Color(0xFFF1F5F9),borderRadius:BorderRadius.circular(4))));}).toList()),const SizedBox(height:12),const Text('A 98-day record of your follow-through.',style:TextStyle(fontSize:12,color:Color(0xFF64748B)))]));}
  Widget habit(HabitItem h){final done=h.completedDates.contains(key(DateTime.now()));return InkWell(onTap:()async{final dates=[...h.completedDates];if(done){dates.remove(key(DateTime.now()));}else{dates.add(key(DateTime.now()));}final i=habits.indexWhere((x)=>x.id==h.id);final next=[...habits]..[i]=h.copyWith(completedDates:dates,streakCount:done?(h.streakCount-1).clamp(0,999).toInt():h.streakCount+1,longestStreak:done?h.longestStreak:(h.streakCount+1>h.longestStreak?h.streakCount+1:h.longestStreak));await StorageService.saveHabits(next);setState(()=>habits=next);},borderRadius:BorderRadius.circular(16),child:Container(margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(16)),child:Row(children:[Text(h.icon,style:const TextStyle(fontSize:24)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(h.title,style:const TextStyle(fontWeight:FontWeight.w700,color:Color(0xFF172033))),Text('${h.category}  •  🔥 ${h.streakCount} day streak',style:const TextStyle(fontSize:12,color:Color(0xFF64748B)))])),Icon(done?Icons.check_circle:Icons.circle_outlined,color:done?const Color(0xFF10B981):const Color(0xFF94A3B8))])));}
  Widget badge(String name,int need,String icon){final unlocked=master>=need;return Container(width:150,padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:unlocked?const Color(0xFFFFF7E8):Colors.white,borderRadius:BorderRadius.circular(16),border:Border.all(color:unlocked?const Color(0xFFFCD34D):const Color(0xFFE2E8F0))),child:Row(children:[Text(unlocked?icon:'🔒'),const SizedBox(width:7),Expanded(child:Text(name,style:TextStyle(fontSize:12,fontWeight:FontWeight.w700,color:unlocked?const Color(0xFF92400E):const Color(0xFF64748B))))]));}
}
